//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int expenseId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public double expense_amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int categoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
